## Importing libraries

In [1]:
import pandas as pd
import numpy as np
import json
import sqlite3

## Data input

In [2]:
with open("employee.json", "r+") as f:
    json_data = json.load(f)
json_data

{'objects': [{'ID': '1',
   'JobTitle': 'Designer',
   'EmailAddress': 'Leroy_Yarlett52@guentu.biz',
   'FirstNameLastName': 'Leroy Yarlett',
   'vaccinated': 'False'},
  {'ID': '2',
   'JobTitle': 'Webmaster',
   'EmailAddress': 'Julian_Gonzales8496@famism.biz',
   'FirstNameLastName': 'Julian Gonzales',
   'vaccinated': 'True'},
  {'ID': '3',
   'JobTitle': 'Paramedic',
   'EmailAddress': 'George_Porter6363@deons.tech',
   'FirstNameLastName': 'George Porter',
   'vaccinated': 'False'},
  {'ID': '4',
   'JobTitle': 'IT Support Staff',
   'EmailAddress': 'Penny_Reynolds8665@supunk.biz',
   'FirstNameLastName': 'Penny Reynolds',
   'vaccinated': 'False'},
  {'ID': '5',
   'JobTitle': 'Dentist',
   'EmailAddress': 'Gabriel_Upton1432@bungar.biz',
   'FirstNameLastName': 'Gabriel Upton',
   'vaccinated': 'True'},
  {'ID': '6',
   'JobTitle': 'Bookkeeper',
   'EmailAddress': 'Rufus_Jeffery8782@mafthy.com',
   'FirstNameLastName': 'Rufus Jeffery',
   'vaccinated': 'True'},
  {'ID': '7',
   'JobTitle': 'Restaurant Manager',
   'EmailAddress': 'Harry_Thomas3263@guentu.biz',
   'FirstNameLastName': 'Harry Thomas',
   'vaccinated': 'False'},
  {'ID': '8',
   'JobTitle': 'Audiologist',
   'EmailAddress': 'Michaela_Little1010@yahoo.com',
   'FirstNameLastName': 'Michaela Little',
   'vaccinated': 'True'},
  {'ID': '9',
   'JobTitle': 'Loan Officer',
   'EmailAddress': 'Mike_Tailor5085@qater.org',
   'FirstNameLastName': 'Mike Tailor',
   'vaccinated': 'False'},
  {'ID': '10',
   'JobTitle': 'Assistant Buyer',
   'EmailAddress': 'Angelina_Haines1218@liret.org',
   'FirstNameLastName': 'Angelina Haines',
   'vaccinated': 'False'},
  {'ID': '11',
   'JobTitle': 'Pharmacist',
   'EmailAddress': 'Goldie_Oakley4929@nanoff.biz',
   'FirstNameLastName': 'Goldie Oakley',
   'vaccinated': 'False'},
  {'ID': '12',
   'JobTitle': 'Global Logistics Supervisor',
   'EmailAddress': 'Sylvia_Marshall5064@vetan.org',
   'FirstNameLastName': 'Sylvia Marshall',
   'vaccinated': 'True'},
  {'ID': '13',
   'JobTitle': 'Restaurant Manager',
   'EmailAddress': 'Mike_Vaughn8880@bulaffy.com',
   'FirstNameLastName': 'Mike Vaughn',
   'vaccinated': 'True'},
  {'ID': '14',
   'JobTitle': 'Machine Operator',
   'EmailAddress': 'Melinda_Shepherd7534@ubusive.com',
   'FirstNameLastName': 'Melinda Shepherd',
   'vaccinated': 'False'},
  {'ID': '15',
   'JobTitle': 'Operator',
   'EmailAddress': 'Doris_Goldsmith6453@famism.biz',
   'FirstNameLastName': 'Doris Goldsmith',
   'vaccinated': 'True'},
  {'ID': '16',
   'JobTitle': 'Associate Professor',
   'EmailAddress': 'Chris_Neal8692@typill.biz',
   'FirstNameLastName': 'Chris Neal',
   'vaccinated': 'False'},
  {'ID': '17',
   'JobTitle': 'Health Educator',
   'EmailAddress': 'Harry_Chester2240@tonsy.org',
   'FirstNameLastName': 'Harry Chester',
   'vaccinated': 'True'},
  {'ID': '18',
   'JobTitle': 'Inspector',
   'EmailAddress': 'Marla_Farrant3348@deons.tech',
   'FirstNameLastName': 'Marla Farrant',
   'vaccinated': 'False'},
  {'ID': '19',
   'JobTitle': 'Fabricator',
   'EmailAddress': 'Tania_Kennedy8370@corti.com',
   'FirstNameLastName': 'Tania Kennedy',
   'vaccinated': 'False'},
  {'ID': '20',
   'JobTitle': 'Retail Trainee',
   'EmailAddress': 'Bryon_Gibbons5610@corti.com',
   'FirstNameLastName': 'Bryon Gibbons',
   'vaccinated': 'False'},
  {'ID': '21',
   'JobTitle': 'Cash Manager',
   'EmailAddress': 'Ivette_Taylor973@extex.org',
   'FirstNameLastName': 'Ivette Taylor',
   'vaccinated': 'False'},
  {'ID': '22',
   'JobTitle': 'HR Coordinator',
   'EmailAddress': 'Chadwick_Eaton1419@twace.org',
   'FirstNameLastName': 'Chadwick Eaton',
   'vaccinated': 'False'},
  {'ID': '23',
   'JobTitle': 'Webmaster',
   'EmailAddress': 'Chuck_Plumb9701@nickia.com',
   'FirstNameLastName': 'Chuck Plumb',
   'vaccinated': 'False'},
  {'ID': '24',
   'JobTitle': 'Steward',
   'EmailAddress': 'Candace_London3099@mafthy.com',
   'FirstNameLastName': 'Candace London',
   'vaccinated': 'False'},
  {'ID': '25',
   'JobTitle': 'Investment  Advisor',
   'EmailAddress': 'Marvin_Wilde6902@cispeto.com',
   'FirstNameLastName': 'Marvin Wilde',
   'vaccinated': 'True'},
  {'ID': '26',
   'JobTitle': 'Doctor',
   'EmailAddress': 'Barry_Taylor950@grannar.com',
   'FirstNameLastName': 'Barry Taylor',
   'vaccinated': 'True'},
  {'ID': '27',
   'JobTitle': 'Bellman',
   'EmailAddress': 'Elijah_Harrison3622@bungar.biz',
   'FirstNameLastName': 'Elijah Harrison',
   'vaccinated': 'False'},
  {'ID': '28',
   'JobTitle': 'Front Desk Coordinator',
   'EmailAddress': 'Jazmin_Mason8297@gembat.biz',
   'FirstNameLastName': 'Jazmin Mason',
   'vaccinated': 'False'},
  {'ID': '29',
   'JobTitle': 'Budget Analyst',
   'EmailAddress': 'Ramon_Whinter4041@elnee.tech',
   'FirstNameLastName': 'Ramon Whinter',
   'vaccinated': 'True'},
  {'ID': '30',
   'JobTitle': 'Doctor',
   'EmailAddress': 'Candace_Darcy6235@jiman.org',
   'FirstNameLastName': 'Candace Darcy',
   'vaccinated': 'False'},
  {'ID': '31',
   'JobTitle': 'Insurance Broker',
   'EmailAddress': 'Leilani_Rose1103@fuliss.net',
   'FirstNameLastName': 'Leilani Rose',
   'vaccinated': 'False'},
  {'ID': '32',
   'JobTitle': 'Software Engineer',
   'EmailAddress': 'Noemi_Miller6490@eirey.tech',
   'FirstNameLastName': 'Noemi Miller',
   'vaccinated': 'True'},
  {'ID': '33',
   'JobTitle': 'Lecturer',
   'EmailAddress': 'Alba_Carson2919@typill.biz',
   'FirstNameLastName': 'Alba Carson',
   'vaccinated': 'True'},
  {'ID': '34',
   'JobTitle': 'Doctor',
   'EmailAddress': 'Russel_Walter1385@bungar.biz',
   'FirstNameLastName': 'Russel Walter',
   'vaccinated': 'True'},
  {'ID': '35',
   'JobTitle': 'Design Engineer',
   'EmailAddress': 'Maia_Kennedy6742@naiker.biz',
   'FirstNameLastName': 'Maia Kennedy',
   'vaccinated': 'False'},
  {'ID': '36',
   'JobTitle': 'Physician',
   'EmailAddress': 'Fred_Clifton2086@infotech44.tech',
   'FirstNameLastName': 'Fred Clifton',
   'vaccinated': 'False'},
  {'ID': '37',
   'JobTitle': 'Call Center Representative',
   'EmailAddress': 'Alexander_Kennedy1766@mafthy.com',
   'FirstNameLastName': 'Alexander Kennedy',
   'vaccinated': 'True'},
  {'ID': '38',
   'JobTitle': 'Systems Administrator',
   'EmailAddress': 'Naomi_Henderson4478@sheye.org',
   'FirstNameLastName': 'Naomi Henderson',
   'vaccinated': 'True'},
  {'ID': '39',
   'JobTitle': 'Biologist',
   'EmailAddress': 'Hank_Howard765@liret.org',
   'FirstNameLastName': 'Hank Howard',
   'vaccinated': 'False'},
  {'ID': '40',
   'JobTitle': 'Steward',
   'EmailAddress': 'Dorothy_Mackenzie4447@deons.tech',
   'FirstNameLastName': 'Dorothy Mackenzie',
   'vaccinated': 'False'},
  {'ID': '41',
   'JobTitle': 'Front Desk Coordinator',
   'EmailAddress': 'Elena_Gregory8402@ubusive.com',
   'FirstNameLastName': 'Elena Gregory',
   'vaccinated': 'True'},
  {'ID': '42',
   'JobTitle': 'Production Painter',
   'EmailAddress': 'Helen_Adams3473@guentu.biz',
   'FirstNameLastName': 'Helen Adams',
   'vaccinated': 'True'},
  {'ID': '43',
   'JobTitle': 'Software Engineer',
   'EmailAddress': 'Lucas_Brooks385@typill.biz',
   'FirstNameLastName': 'Lucas Brooks',
   'vaccinated': 'False'},
  {'ID': '44',
   'JobTitle': 'Cook',
   'EmailAddress': 'Angelina_Ross7491@qater.org',
   'FirstNameLastName': 'Angelina Ross',
   'vaccinated': 'True'},
  {'ID': '45',
   'JobTitle': 'Biologist',
   'EmailAddress': 'Remy_Benfield4958@kideod.biz',
   'FirstNameLastName': 'Remy Benfield',
   'vaccinated': 'True'},
  {'ID': '46',
   'JobTitle': 'IT Support Staff',
   'EmailAddress': 'Mackenzie_Neal4273@qater.org',
   'FirstNameLastName': 'Mackenzie Neal',
   'vaccinated': 'True'},
  {'ID': '47',
   'JobTitle': 'Associate Professor',
   'EmailAddress': 'Janelle_Parker3414@twace.org',
   'FirstNameLastName': 'Janelle Parker',
   'vaccinated': 'True'},
  {'ID': '48',
   'JobTitle': 'Treasurer',
   'EmailAddress': 'Matthew_Woodley2830@gembat.biz',
   'FirstNameLastName': 'Matthew Woodley',
   'vaccinated': 'True'},
  {'ID': '49',
   'JobTitle': 'Ambulatory Nurse',
   'EmailAddress': 'Anthony_Coleman4896@nanoff.biz',
   'FirstNameLastName': 'Anthony Coleman',
   'vaccinated': 'True'},
  {'ID': '50',
   'JobTitle': 'Restaurant Manager',
   'EmailAddress': 'Peyton_Hobson4407@iatim.tech',
   'FirstNameLastName': 'Peyton Hobson',
   'vaccinated': 'True'}]}

In [3]:
type(json_data)

dict

In [4]:
json_data.keys()

dict_keys(['objects'])

In [5]:
json_data.values()

dict_values([[{'ID': '1', 'JobTitle': 'Designer', 'EmailAddress': 'Leroy_Yarlett52@guentu.biz', 'FirstNameLastName': 'Leroy Yarlett', 'vaccinated': 'False'}, {'ID': '2', 'JobTitle': 'Webmaster', 'EmailAddress': 'Julian_Gonzales8496@famism.biz', 'FirstNameLastName': 'Julian Gonzales', 'vaccinated': 'True'}, {'ID': '3', 'JobTitle': 'Paramedic', 'EmailAddress': 'George_Porter6363@deons.tech', 'FirstNameLastName': 'George Porter', 'vaccinated': 'False'}, {'ID': '4', 'JobTitle': 'IT Support Staff', 'EmailAddress': 'Penny_Reynolds8665@supunk.biz', 'FirstNameLastName': 'Penny Reynolds', 'vaccinated': 'False'}, {'ID': '5', 'JobTitle': 'Dentist', 'EmailAddress': 'Gabriel_Upton1432@bungar.biz', 'FirstNameLastName': 'Gabriel Upton', 'vaccinated': 'True'}, {'ID': '6', 'JobTitle': 'Bookkeeper', 'EmailAddress': 'Rufus_Jeffery8782@mafthy.com', 'FirstNameLastName': 'Rufus Jeffery', 'vaccinated': 'True'}, {'ID': '7', 'JobTitle': 'Restaurant Manager', 'EmailAddress': 'Harry_Thomas3263@guentu.biz', 'FirstNameLastName': 'Harry Thomas', 'vaccinated': 'False'}, {'ID': '8', 'JobTitle': 'Audiologist', 'EmailAddress': 'Michaela_Little1010@yahoo.com', 'FirstNameLastName': 'Michaela Little', 'vaccinated': 'True'}, {'ID': '9', 'JobTitle': 'Loan Officer', 'EmailAddress': 'Mike_Tailor5085@qater.org', 'FirstNameLastName': 'Mike Tailor', 'vaccinated': 'False'}, {'ID': '10', 'JobTitle': 'Assistant Buyer', 'EmailAddress': 'Angelina_Haines1218@liret.org', 'FirstNameLastName': 'Angelina Haines', 'vaccinated': 'False'}, {'ID': '11', 'JobTitle': 'Pharmacist', 'EmailAddress': 'Goldie_Oakley4929@nanoff.biz', 'FirstNameLastName': 'Goldie Oakley', 'vaccinated': 'False'}, {'ID': '12', 'JobTitle': 'Global Logistics Supervisor', 'EmailAddress': 'Sylvia_Marshall5064@vetan.org', 'FirstNameLastName': 'Sylvia Marshall', 'vaccinated': 'True'}, {'ID': '13', 'JobTitle': 'Restaurant Manager', 'EmailAddress': 'Mike_Vaughn8880@bulaffy.com', 'FirstNameLastName': 'Mike Vaughn', 'vaccinated': 'True'}, {'ID': '14', 'JobTitle': 'Machine Operator', 'EmailAddress': 'Melinda_Shepherd7534@ubusive.com', 'FirstNameLastName': 'Melinda Shepherd', 'vaccinated': 'False'}, {'ID': '15', 'JobTitle': 'Operator', 'EmailAddress': 'Doris_Goldsmith6453@famism.biz', 'FirstNameLastName': 'Doris Goldsmith', 'vaccinated': 'True'}, {'ID': '16', 'JobTitle': 'Associate Professor', 'EmailAddress': 'Chris_Neal8692@typill.biz', 'FirstNameLastName': 'Chris Neal', 'vaccinated': 'False'}, {'ID': '17', 'JobTitle': 'Health Educator', 'EmailAddress': 'Harry_Chester2240@tonsy.org', 'FirstNameLastName': 'Harry Chester', 'vaccinated': 'True'}, {'ID': '18', 'JobTitle': 'Inspector', 'EmailAddress': 'Marla_Farrant3348@deons.tech', 'FirstNameLastName': 'Marla Farrant', 'vaccinated': 'False'}, {'ID': '19', 'JobTitle': 'Fabricator', 'EmailAddress': 'Tania_Kennedy8370@corti.com', 'FirstNameLastName': 'Tania Kennedy', 'vaccinated': 'False'}, {'ID': '20', 'JobTitle': 'Retail Trainee', 'EmailAddress': 'Bryon_Gibbons5610@corti.com', 'FirstNameLastName': 'Bryon Gibbons', 'vaccinated': 'False'}, {'ID': '21', 'JobTitle': 'Cash Manager', 'EmailAddress': 'Ivette_Taylor973@extex.org', 'FirstNameLastName': 'Ivette Taylor', 'vaccinated': 'False'}, {'ID': '22', 'JobTitle': 'HR Coordinator', 'EmailAddress': 'Chadwick_Eaton1419@twace.org', 'FirstNameLastName': 'Chadwick Eaton', 'vaccinated': 'False'}, {'ID': '23', 'JobTitle': 'Webmaster', 'EmailAddress': 'Chuck_Plumb9701@nickia.com', 'FirstNameLastName': 'Chuck Plumb', 'vaccinated': 'False'}, {'ID': '24', 'JobTitle': 'Steward', 'EmailAddress': 'Candace_London3099@mafthy.com', 'FirstNameLastName': 'Candace London', 'vaccinated': 'False'}, {'ID': '25', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Marvin_Wilde6902@cispeto.com', 'FirstNameLastName': 'Marvin Wilde', 'vaccinated': 'True'}, {'ID': '26', 'JobTitle': 'Doctor', 'EmailAddress': 'Barry_Taylor950@grannar.com', 'FirstNameLastName': 'Barry Taylor', 'vaccinated': 'True'}, {'ID': '27', 'JobTitle': 'Bellman', 'EmailAddress': 'Elijah_Harrison3622@bungar.biz', 'FirstNameLastName': 'Elijah Harrison', 'vaccinated': 'False'}, {'ID': '28', 'JobTitle': 'Front Desk Coordinator', 'EmailAddress': 'Jazmin_Mason8297@gembat.biz', 'FirstNameLastName': 'Jazmin Mason', 'vaccinated': 'False'}, {'ID': '29', 'JobTitle': 'Budget Analyst', 'EmailAddress': 'Ramon_Whinter4041@elnee.tech', 'FirstNameLastName': 'Ramon Whinter', 'vaccinated': 'True'}, {'ID': '30', 'JobTitle': 'Doctor', 'EmailAddress': 'Candace_Darcy6235@jiman.org', 'FirstNameLastName': 'Candace Darcy', 'vaccinated': 'False'}, {'ID': '31', 'JobTitle': 'Insurance Broker', 'EmailAddress': 'Leilani_Rose1103@fuliss.net', 'FirstNameLastName': 'Leilani Rose', 'vaccinated': 'False'}, {'ID': '32', 'JobTitle': 'Software Engineer', 'EmailAddress': 'Noemi_Miller6490@eirey.tech', 'FirstNameLastName': 'Noemi Miller', 'vaccinated': 'True'}, {'ID': '33', 'JobTitle': 'Lecturer', 'EmailAddress': 'Alba_Carson2919@typill.biz', 'FirstNameLastName': 'Alba Carson', 'vaccinated': 'True'}, {'ID': '34', 'JobTitle': 'Doctor', 'EmailAddress': 'Russel_Walter1385@bungar.biz', 'FirstNameLastName': 'Russel Walter', 'vaccinated': 'True'}, {'ID': '35', 'JobTitle': 'Design Engineer', 'EmailAddress': 'Maia_Kennedy6742@naiker.biz', 'FirstNameLastName': 'Maia Kennedy', 'vaccinated': 'False'}, {'ID': '36', 'JobTitle': 'Physician', 'EmailAddress': 'Fred_Clifton2086@infotech44.tech', 'FirstNameLastName': 'Fred Clifton', 'vaccinated': 'False'}, {'ID': '37', 'JobTitle': 'Call Center Representative', 'EmailAddress': 'Alexander_Kennedy1766@mafthy.com', 'FirstNameLastName': 'Alexander Kennedy', 'vaccinated': 'True'}, {'ID': '38', 'JobTitle': 'Systems Administrator', 'EmailAddress': 'Naomi_Henderson4478@sheye.org', 'FirstNameLastName': 'Naomi Henderson', 'vaccinated': 'True'}, {'ID': '39', 'JobTitle': 'Biologist', 'EmailAddress': 'Hank_Howard765@liret.org', 'FirstNameLastName': 'Hank Howard', 'vaccinated': 'False'}, {'ID': '40', 'JobTitle': 'Steward', 'EmailAddress': 'Dorothy_Mackenzie4447@deons.tech', 'FirstNameLastName': 'Dorothy Mackenzie', 'vaccinated': 'False'}, {'ID': '41', 'JobTitle': 'Front Desk Coordinator', 'EmailAddress': 'Elena_Gregory8402@ubusive.com', 'FirstNameLastName': 'Elena Gregory', 'vaccinated': 'True'}, {'ID': '42', 'JobTitle': 'Production Painter', 'EmailAddress': 'Helen_Adams3473@guentu.biz', 'FirstNameLastName': 'Helen Adams', 'vaccinated': 'True'}, {'ID': '43', 'JobTitle': 'Software Engineer', 'EmailAddress': 'Lucas_Brooks385@typill.biz', 'FirstNameLastName': 'Lucas Brooks', 'vaccinated': 'False'}, {'ID': '44', 'JobTitle': 'Cook', 'EmailAddress': 'Angelina_Ross7491@qater.org', 'FirstNameLastName': 'Angelina Ross', 'vaccinated': 'True'}, {'ID': '45', 'JobTitle': 'Biologist', 'EmailAddress': 'Remy_Benfield4958@kideod.biz', 'FirstNameLastName': 'Remy Benfield', 'vaccinated': 'True'}, {'ID': '46', 'JobTitle': 'IT Support Staff', 'EmailAddress': 'Mackenzie_Neal4273@qater.org', 'FirstNameLastName': 'Mackenzie Neal', 'vaccinated': 'True'}, {'ID': '47', 'JobTitle': 'Associate Professor', 'EmailAddress': 'Janelle_Parker3414@twace.org', 'FirstNameLastName': 'Janelle Parker', 'vaccinated': 'True'}, {'ID': '48', 'JobTitle': 'Treasurer', 'EmailAddress': 'Matthew_Woodley2830@gembat.biz', 'FirstNameLastName': 'Matthew Woodley', 'vaccinated': 'True'}, {'ID': '49', 'JobTitle': 'Ambulatory Nurse', 'EmailAddress': 'Anthony_Coleman4896@nanoff.biz', 'FirstNameLastName': 'Anthony Coleman', 'vaccinated': 'True'}, {'ID': '50', 'JobTitle': 'Restaurant Manager', 'EmailAddress': 'Peyton_Hobson4407@iatim.tech', 'FirstNameLastName': 'Peyton Hobson', 'vaccinated': 'True'}]])

In [6]:
value = {}
for item in json_data.values():
    value = item
value

[{'ID': '1',
  'JobTitle': 'Designer',
  'EmailAddress': 'Leroy_Yarlett52@guentu.biz',
  'FirstNameLastName': 'Leroy Yarlett',
  'vaccinated': 'False'},
 {'ID': '2',
  'JobTitle': 'Webmaster',
  'EmailAddress': 'Julian_Gonzales8496@famism.biz',
  'FirstNameLastName': 'Julian Gonzales',
  'vaccinated': 'True'},
 {'ID': '3',
  'JobTitle': 'Paramedic',
  'EmailAddress': 'George_Porter6363@deons.tech',
  'FirstNameLastName': 'George Porter',
  'vaccinated': 'False'},
 {'ID': '4',
  'JobTitle': 'IT Support Staff',
  'EmailAddress': 'Penny_Reynolds8665@supunk.biz',
  'FirstNameLastName': 'Penny Reynolds',
  'vaccinated': 'False'},
 {'ID': '5',
  'JobTitle': 'Dentist',
  'EmailAddress': 'Gabriel_Upton1432@bungar.biz',
  'FirstNameLastName': 'Gabriel Upton',
  'vaccinated': 'True'},
 {'ID': '6',
  'JobTitle': 'Bookkeeper',
  'EmailAddress': 'Rufus_Jeffery8782@mafthy.com',
  'FirstNameLastName': 'Rufus Jeffery',
  'vaccinated': 'True'},
 {'ID': '7',
  'JobTitle': 'Restaurant Manager',
  'EmailAddress': 'Harry_Thomas3263@guentu.biz',
  'FirstNameLastName': 'Harry Thomas',
  'vaccinated': 'False'},
 {'ID': '8',
  'JobTitle': 'Audiologist',
  'EmailAddress': 'Michaela_Little1010@yahoo.com',
  'FirstNameLastName': 'Michaela Little',
  'vaccinated': 'True'},
 {'ID': '9',
  'JobTitle': 'Loan Officer',
  'EmailAddress': 'Mike_Tailor5085@qater.org',
  'FirstNameLastName': 'Mike Tailor',
  'vaccinated': 'False'},
 {'ID': '10',
  'JobTitle': 'Assistant Buyer',
  'EmailAddress': 'Angelina_Haines1218@liret.org',
  'FirstNameLastName': 'Angelina Haines',
  'vaccinated': 'False'},
 {'ID': '11',
  'JobTitle': 'Pharmacist',
  'EmailAddress': 'Goldie_Oakley4929@nanoff.biz',
  'FirstNameLastName': 'Goldie Oakley',
  'vaccinated': 'False'},
 {'ID': '12',
  'JobTitle': 'Global Logistics Supervisor',
  'EmailAddress': 'Sylvia_Marshall5064@vetan.org',
  'FirstNameLastName': 'Sylvia Marshall',
  'vaccinated': 'True'},
 {'ID': '13',
  'JobTitle': 'Restaurant Manager',
  'EmailAddress': 'Mike_Vaughn8880@bulaffy.com',
  'FirstNameLastName': 'Mike Vaughn',
  'vaccinated': 'True'},
 {'ID': '14',
  'JobTitle': 'Machine Operator',
  'EmailAddress': 'Melinda_Shepherd7534@ubusive.com',
  'FirstNameLastName': 'Melinda Shepherd',
  'vaccinated': 'False'},
 {'ID': '15',
  'JobTitle': 'Operator',
  'EmailAddress': 'Doris_Goldsmith6453@famism.biz',
  'FirstNameLastName': 'Doris Goldsmith',
  'vaccinated': 'True'},
 {'ID': '16',
  'JobTitle': 'Associate Professor',
  'EmailAddress': 'Chris_Neal8692@typill.biz',
  'FirstNameLastName': 'Chris Neal',
  'vaccinated': 'False'},
 {'ID': '17',
  'JobTitle': 'Health Educator',
  'EmailAddress': 'Harry_Chester2240@tonsy.org',
  'FirstNameLastName': 'Harry Chester',
  'vaccinated': 'True'},
 {'ID': '18',
  'JobTitle': 'Inspector',
  'EmailAddress': 'Marla_Farrant3348@deons.tech',
  'FirstNameLastName': 'Marla Farrant',
  'vaccinated': 'False'},
 {'ID': '19',
  'JobTitle': 'Fabricator',
  'EmailAddress': 'Tania_Kennedy8370@corti.com',
  'FirstNameLastName': 'Tania Kennedy',
  'vaccinated': 'False'},
 {'ID': '20',
  'JobTitle': 'Retail Trainee',
  'EmailAddress': 'Bryon_Gibbons5610@corti.com',
  'FirstNameLastName': 'Bryon Gibbons',
  'vaccinated': 'False'},
 {'ID': '21',
  'JobTitle': 'Cash Manager',
  'EmailAddress': 'Ivette_Taylor973@extex.org',
  'FirstNameLastName': 'Ivette Taylor',
  'vaccinated': 'False'},
 {'ID': '22',
  'JobTitle': 'HR Coordinator',
  'EmailAddress': 'Chadwick_Eaton1419@twace.org',
  'FirstNameLastName': 'Chadwick Eaton',
  'vaccinated': 'False'},
 {'ID': '23',
  'JobTitle': 'Webmaster',
  'EmailAddress': 'Chuck_Plumb9701@nickia.com',
  'FirstNameLastName': 'Chuck Plumb',
  'vaccinated': 'False'},
 {'ID': '24',
  'JobTitle': 'Steward',
  'EmailAddress': 'Candace_London3099@mafthy.com',
  'FirstNameLastName': 'Candace London',
  'vaccinated': 'False'},
 {'ID': '25',
  'JobTitle': 'Investment  Advisor',
  'EmailAddress': 'Marvin_Wilde6902@cispeto.com',
  'FirstNameLastName': 'Marvin Wilde',
  'vaccinated': 'True'},
 {'ID': '26',
  'JobTitle': 'Doctor',
  'EmailAddress': 'Barry_Taylor950@grannar.com',
  'FirstNameLastName': 'Barry Taylor',
  'vaccinated': 'True'},
 {'ID': '27',
  'JobTitle': 'Bellman',
  'EmailAddress': 'Elijah_Harrison3622@bungar.biz',
  'FirstNameLastName': 'Elijah Harrison',
  'vaccinated': 'False'},
 {'ID': '28',
  'JobTitle': 'Front Desk Coordinator',
  'EmailAddress': 'Jazmin_Mason8297@gembat.biz',
  'FirstNameLastName': 'Jazmin Mason',
  'vaccinated': 'False'},
 {'ID': '29',
  'JobTitle': 'Budget Analyst',
  'EmailAddress': 'Ramon_Whinter4041@elnee.tech',
  'FirstNameLastName': 'Ramon Whinter',
  'vaccinated': 'True'},
 {'ID': '30',
  'JobTitle': 'Doctor',
  'EmailAddress': 'Candace_Darcy6235@jiman.org',
  'FirstNameLastName': 'Candace Darcy',
  'vaccinated': 'False'},
 {'ID': '31',
  'JobTitle': 'Insurance Broker',
  'EmailAddress': 'Leilani_Rose1103@fuliss.net',
  'FirstNameLastName': 'Leilani Rose',
  'vaccinated': 'False'},
 {'ID': '32',
  'JobTitle': 'Software Engineer',
  'EmailAddress': 'Noemi_Miller6490@eirey.tech',
  'FirstNameLastName': 'Noemi Miller',
  'vaccinated': 'True'},
 {'ID': '33',
  'JobTitle': 'Lecturer',
  'EmailAddress': 'Alba_Carson2919@typill.biz',
  'FirstNameLastName': 'Alba Carson',
  'vaccinated': 'True'},
 {'ID': '34',
  'JobTitle': 'Doctor',
  'EmailAddress': 'Russel_Walter1385@bungar.biz',
  'FirstNameLastName': 'Russel Walter',
  'vaccinated': 'True'},
 {'ID': '35',
  'JobTitle': 'Design Engineer',
  'EmailAddress': 'Maia_Kennedy6742@naiker.biz',
  'FirstNameLastName': 'Maia Kennedy',
  'vaccinated': 'False'},
 {'ID': '36',
  'JobTitle': 'Physician',
  'EmailAddress': 'Fred_Clifton2086@infotech44.tech',
  'FirstNameLastName': 'Fred Clifton',
  'vaccinated': 'False'},
 {'ID': '37',
  'JobTitle': 'Call Center Representative',
  'EmailAddress': 'Alexander_Kennedy1766@mafthy.com',
  'FirstNameLastName': 'Alexander Kennedy',
  'vaccinated': 'True'},
 {'ID': '38',
  'JobTitle': 'Systems Administrator',
  'EmailAddress': 'Naomi_Henderson4478@sheye.org',
  'FirstNameLastName': 'Naomi Henderson',
  'vaccinated': 'True'},
 {'ID': '39',
  'JobTitle': 'Biologist',
  'EmailAddress': 'Hank_Howard765@liret.org',
  'FirstNameLastName': 'Hank Howard',
  'vaccinated': 'False'},
 {'ID': '40',
  'JobTitle': 'Steward',
  'EmailAddress': 'Dorothy_Mackenzie4447@deons.tech',
  'FirstNameLastName': 'Dorothy Mackenzie',
  'vaccinated': 'False'},
 {'ID': '41',
  'JobTitle': 'Front Desk Coordinator',
  'EmailAddress': 'Elena_Gregory8402@ubusive.com',
  'FirstNameLastName': 'Elena Gregory',
  'vaccinated': 'True'},
 {'ID': '42',
  'JobTitle': 'Production Painter',
  'EmailAddress': 'Helen_Adams3473@guentu.biz',
  'FirstNameLastName': 'Helen Adams',
  'vaccinated': 'True'},
 {'ID': '43',
  'JobTitle': 'Software Engineer',
  'EmailAddress': 'Lucas_Brooks385@typill.biz',
  'FirstNameLastName': 'Lucas Brooks',
  'vaccinated': 'False'},
 {'ID': '44',
  'JobTitle': 'Cook',
  'EmailAddress': 'Angelina_Ross7491@qater.org',
  'FirstNameLastName': 'Angelina Ross',
  'vaccinated': 'True'},
 {'ID': '45',
  'JobTitle': 'Biologist',
  'EmailAddress': 'Remy_Benfield4958@kideod.biz',
  'FirstNameLastName': 'Remy Benfield',
  'vaccinated': 'True'},
 {'ID': '46',
  'JobTitle': 'IT Support Staff',
  'EmailAddress': 'Mackenzie_Neal4273@qater.org',
  'FirstNameLastName': 'Mackenzie Neal',
  'vaccinated': 'True'},
 {'ID': '47',
  'JobTitle': 'Associate Professor',
  'EmailAddress': 'Janelle_Parker3414@twace.org',
  'FirstNameLastName': 'Janelle Parker',
  'vaccinated': 'True'},
 {'ID': '48',
  'JobTitle': 'Treasurer',
  'EmailAddress': 'Matthew_Woodley2830@gembat.biz',
  'FirstNameLastName': 'Matthew Woodley',
  'vaccinated': 'True'},
 {'ID': '49',
  'JobTitle': 'Ambulatory Nurse',
  'EmailAddress': 'Anthony_Coleman4896@nanoff.biz',
  'FirstNameLastName': 'Anthony Coleman',
  'vaccinated': 'True'},
 {'ID': '50',
  'JobTitle': 'Restaurant Manager',
  'EmailAddress': 'Peyton_Hobson4407@iatim.tech',
  'FirstNameLastName': 'Peyton Hobson',
  'vaccinated': 'True'}]

## Converting JSON Data into DataFrame

In [7]:
df = pd.DataFrame(value)
df.head(5)

,ID,JobTitle,EmailAddress,FirstNameLastName,vaccinated
0,1,Designer,Leroy_Yarlett52@guentu.biz,Leroy Yarlett,False
1,2,Webmaster,Julian_Gonzales8496@famism.biz,Julian Gonzales,True
2,3,Paramedic,George_Porter6363@deons.tech,George Porter,False
3,4,IT Support Staff,Penny_Reynolds8665@supunk.biz,Penny Reynolds,False
4,5,Dentist,Gabriel_Upton1432@bungar.biz,Gabriel Upton,True

In [8]:
df.columns

Index(['ID', 'JobTitle', 'EmailAddress', 'FirstNameLastName', 'vaccinated'], dtype='object')

## converting DataFrame columns into lists

In [9]:
id_df = df['ID'].tolist()
job_title_df = df['JobTitle'].tolist()
email_address_df = df['EmailAddress'].tolist()
firstname_lastname_df = df['FirstNameLastName'].tolist()
vaccinated_df = df['vaccinated'].tolist()

In [10]:
id_df = [eval(i) for i in id_df]
id_df

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [11]:
## setting len of list
n = len(id_df)

## SQLITE Setup

In [12]:
connection = sqlite3.connect("data.db")

In [13]:
csr = connection.cursor()

#### creating new table employee

In [14]:
sql_command_create_emp_table = """ CREATE TABLE employee (
id INTEGER PRIMARY KEY,
JobTitle VARCHAR(100),
EmailAddress VARCHAR(100),
FirstNameLastName VARCHAR(100),
vaccinated BOOLEAN
)"""

csr.execute(sql_command_create_emp_table)

#### setting values for table employee

In [15]:
for i in range(n):
    csr.execute("""INSERT INTO employee(id, JobTitle, EmailAddress, FirstNameLastName, vaccinated) VALUES (?,?,?,?,?);""",(id_df[i], job_title_df[i], email_address_df[i], firstname_lastname_df[i], vaccinated_df[i]))

#### Fetching Data

In [16]:
csr.execute("SELECT * FROM employee")
ans = csr.fetchall()
for i in ans:
    print(i)

(1, 'Designer', 'Leroy_Yarlett52@guentu.biz', 'Leroy Yarlett', 'False')
(2, 'Webmaster', 'Julian_Gonzales8496@famism.biz', 'Julian Gonzales', 'True')
(3, 'Paramedic', 'George_Porter6363@deons.tech', 'George Porter', 'False')
(4, 'IT Support Staff', 'Penny_Reynolds8665@supunk.biz', 'Penny Reynolds', 'False')
(5, 'Dentist', 'Gabriel_Upton1432@bungar.biz', 'Gabriel Upton', 'True')
(6, 'Bookkeeper', 'Rufus_Jeffery8782@mafthy.com', 'Rufus Jeffery', 'True')
(7, 'Restaurant Manager', 'Harry_Thomas3263@guentu.biz', 'Harry Thomas', 'False')
(8, 'Audiologist', 'Michaela_Little1010@yahoo.com', 'Michaela Little', 'True')
(9, 'Loan Officer', 'Mike_Tailor5085@qater.org', 'Mike Tailor', 'False')
(10, 'Assistant Buyer', 'Angelina_Haines1218@liret.org', 'Angelina Haines', 'False')
(11, 'Pharmacist', 'Goldie_Oakley4929@nanoff.biz', 'Goldie Oakley', 'False')
(12, 'Global Logistics Supervisor', 'Sylvia_Marshall5064@vetan.org', 'Sylvia Marshall', 'True')
(13, 'Restaurant Manager', 'Mike_Vaughn8880@bulaffy.com', 'Mike Vaughn', 'True')
(14, 'Machine Operator', 'Melinda_Shepherd7534@ubusive.com', 'Melinda Shepherd', 'False')
(15, 'Operator', 'Doris_Goldsmith6453@famism.biz', 'Doris Goldsmith', 'True')
(16, 'Associate Professor', 'Chris_Neal8692@typill.biz', 'Chris Neal', 'False')
(17, 'Health Educator', 'Harry_Chester2240@tonsy.org', 'Harry Chester', 'True')
(18, 'Inspector', 'Marla_Farrant3348@deons.tech', 'Marla Farrant', 'False')
(19, 'Fabricator', 'Tania_Kennedy8370@corti.com', 'Tania Kennedy', 'False')
(20, 'Retail Trainee', 'Bryon_Gibbons5610@corti.com', 'Bryon Gibbons', 'False')
(21, 'Cash Manager', 'Ivette_Taylor973@extex.org', 'Ivette Taylor', 'False')
(22, 'HR Coordinator', 'Chadwick_Eaton1419@twace.org', 'Chadwick Eaton', 'False')
(23, 'Webmaster', 'Chuck_Plumb9701@nickia.com', 'Chuck Plumb', 'False')
(24, 'Steward', 'Candace_London3099@mafthy.com', 'Candace London', 'False')
(25, 'Investment  Advisor', 'Marvin_Wilde6902@cispeto.com', 'Marvin Wilde', 'True')
(26, 'Doctor', 'Barry_Taylor950@grannar.com', 'Barry Taylor', 'True')
(27, 'Bellman', 'Elijah_Harrison3622@bungar.biz', 'Elijah Harrison', 'False')
(28, 'Front Desk Coordinator', 'Jazmin_Mason8297@gembat.biz', 'Jazmin Mason', 'False')
(29, 'Budget Analyst', 'Ramon_Whinter4041@elnee.tech', 'Ramon Whinter', 'True')
(30, 'Doctor', 'Candace_Darcy6235@jiman.org', 'Candace Darcy', 'False')
(31, 'Insurance Broker', 'Leilani_Rose1103@fuliss.net', 'Leilani Rose', 'False')
(32, 'Software Engineer', 'Noemi_Miller6490@eirey.tech', 'Noemi Miller', 'True')
(33, 'Lecturer', 'Alba_Carson2919@typill.biz', 'Alba Carson', 'True')
(34, 'Doctor', 'Russel_Walter1385@bungar.biz', 'Russel Walter', 'True')
(35, 'Design Engineer', 'Maia_Kennedy6742@naiker.biz', 'Maia Kennedy', 'False')
(36, 'Physician', 'Fred_Clifton2086@infotech44.tech', 'Fred Clifton', 'False')
(37, 'Call Center Representative', 'Alexander_Kennedy1766@mafthy.com', 'Alexander Kennedy', 'True')
(38, 'Systems Administrator', 'Naomi_Henderson4478@sheye.org', 'Naomi Henderson', 'True')
(39, 'Biologist', 'Hank_Howard765@liret.org', 'Hank Howard', 'False')
(40, 'Steward', 'Dorothy_Mackenzie4447@deons.tech', 'Dorothy Mackenzie', 'False')
(41, 'Front Desk Coordinator', 'Elena_Gregory8402@ubusive.com', 'Elena Gregory', 'True')
(42, 'Production Painter', 'Helen_Adams3473@guentu.biz', 'Helen Adams', 'True')
(43, 'Software Engineer', 'Lucas_Brooks385@typill.biz', 'Lucas Brooks', 'False')
(44, 'Cook', 'Angelina_Ross7491@qater.org', 'Angelina Ross', 'True')
(45, 'Biologist', 'Remy_Benfield4958@kideod.biz', 'Remy Benfield', 'True')
(46, 'IT Support Staff', 'Mackenzie_Neal4273@qater.org', 'Mackenzie Neal', 'True')
(47, 'Associate Professor', 'Janelle_Parker3414@twace.org', 'Janelle Parker', 'True')
(48, 'Treasurer', 'Matthew_Woodley2830@gembat.biz', 'Matthew Woodley', 'True')
(49, 'Ambulatory Nurse', 'Anthony_Coleman4896@nanoff.biz', 'Anthony Coleman', 'True')
(50, 'Restaurant Manager', 'Peyton_Hobson4407@iatim.tech', 'Peyton Hobson', 'True')

In [17]:
## All columns in table "employee"
data = csr.execute('''SELECT * FROM employee''')
for column in data.description:
    print(column[0])

id
JobTitle
EmailAddress
FirstNameLastName
vaccinated

#### adding new column 'bonus percent' for giving bonus percent
#### - percent is 15% if person is vaccinated
#### - percent is 5 % if person is not vaccinated

In [18]:
### adding new column

csr.execute(f"""
ALTER TABLE employee 
ADD COLUMN bonus_percent INTEGER
""")

In [19]:
### setting data for column - bonus_percent as 15 for people with vaccinated=True
csr.execute("""
UPDATE employee
SET bonus_percent = 15
WHERE vaccinated = 'True'
""")

In [20]:
### setting data for column - bonus_percent as 5 for people with vaccinated=False
csr.execute("""
UPDATE employee
SET bonus_percent = 5
WHERE vaccinated = 'False'
""")

In [21]:
## fetching data
csr.execute("SELECT * FROM employee")
ans = csr.fetchall()
for i in ans:
    print(i)

(1, 'Designer', 'Leroy_Yarlett52@guentu.biz', 'Leroy Yarlett', 'False', 5)
(2, 'Webmaster', 'Julian_Gonzales8496@famism.biz', 'Julian Gonzales', 'True', 15)
(3, 'Paramedic', 'George_Porter6363@deons.tech', 'George Porter', 'False', 5)
(4, 'IT Support Staff', 'Penny_Reynolds8665@supunk.biz', 'Penny Reynolds', 'False', 5)
(5, 'Dentist', 'Gabriel_Upton1432@bungar.biz', 'Gabriel Upton', 'True', 15)
(6, 'Bookkeeper', 'Rufus_Jeffery8782@mafthy.com', 'Rufus Jeffery', 'True', 15)
(7, 'Restaurant Manager', 'Harry_Thomas3263@guentu.biz', 'Harry Thomas', 'False', 5)
(8, 'Audiologist', 'Michaela_Little1010@yahoo.com', 'Michaela Little', 'True', 15)
(9, 'Loan Officer', 'Mike_Tailor5085@qater.org', 'Mike Tailor', 'False', 5)
(10, 'Assistant Buyer', 'Angelina_Haines1218@liret.org', 'Angelina Haines', 'False', 5)
(11, 'Pharmacist', 'Goldie_Oakley4929@nanoff.biz', 'Goldie Oakley', 'False', 5)
(12, 'Global Logistics Supervisor', 'Sylvia_Marshall5064@vetan.org', 'Sylvia Marshall', 'True', 15)
(13, 'Restaurant Manager', 'Mike_Vaughn8880@bulaffy.com', 'Mike Vaughn', 'True', 15)
(14, 'Machine Operator', 'Melinda_Shepherd7534@ubusive.com', 'Melinda Shepherd', 'False', 5)
(15, 'Operator', 'Doris_Goldsmith6453@famism.biz', 'Doris Goldsmith', 'True', 15)
(16, 'Associate Professor', 'Chris_Neal8692@typill.biz', 'Chris Neal', 'False', 5)
(17, 'Health Educator', 'Harry_Chester2240@tonsy.org', 'Harry Chester', 'True', 15)
(18, 'Inspector', 'Marla_Farrant3348@deons.tech', 'Marla Farrant', 'False', 5)
(19, 'Fabricator', 'Tania_Kennedy8370@corti.com', 'Tania Kennedy', 'False', 5)
(20, 'Retail Trainee', 'Bryon_Gibbons5610@corti.com', 'Bryon Gibbons', 'False', 5)
(21, 'Cash Manager', 'Ivette_Taylor973@extex.org', 'Ivette Taylor', 'False', 5)
(22, 'HR Coordinator', 'Chadwick_Eaton1419@twace.org', 'Chadwick Eaton', 'False', 5)
(23, 'Webmaster', 'Chuck_Plumb9701@nickia.com', 'Chuck Plumb', 'False', 5)
(24, 'Steward', 'Candace_London3099@mafthy.com', 'Candace London', 'False', 5)
(25, 'Investment  Advisor', 'Marvin_Wilde6902@cispeto.com', 'Marvin Wilde', 'True', 15)
(26, 'Doctor', 'Barry_Taylor950@grannar.com', 'Barry Taylor', 'True', 15)
(27, 'Bellman', 'Elijah_Harrison3622@bungar.biz', 'Elijah Harrison', 'False', 5)
(28, 'Front Desk Coordinator', 'Jazmin_Mason8297@gembat.biz', 'Jazmin Mason', 'False', 5)
(29, 'Budget Analyst', 'Ramon_Whinter4041@elnee.tech', 'Ramon Whinter', 'True', 15)
(30, 'Doctor', 'Candace_Darcy6235@jiman.org', 'Candace Darcy', 'False', 5)
(31, 'Insurance Broker', 'Leilani_Rose1103@fuliss.net', 'Leilani Rose', 'False', 5)
(32, 'Software Engineer', 'Noemi_Miller6490@eirey.tech', 'Noemi Miller', 'True', 15)
(33, 'Lecturer', 'Alba_Carson2919@typill.biz', 'Alba Carson', 'True', 15)
(34, 'Doctor', 'Russel_Walter1385@bungar.biz', 'Russel Walter', 'True', 15)
(35, 'Design Engineer', 'Maia_Kennedy6742@naiker.biz', 'Maia Kennedy', 'False', 5)
(36, 'Physician', 'Fred_Clifton2086@infotech44.tech', 'Fred Clifton', 'False', 5)
(37, 'Call Center Representative', 'Alexander_Kennedy1766@mafthy.com', 'Alexander Kennedy', 'True', 15)
(38, 'Systems Administrator', 'Naomi_Henderson4478@sheye.org', 'Naomi Henderson', 'True', 15)
(39, 'Biologist', 'Hank_Howard765@liret.org', 'Hank Howard', 'False', 5)
(40, 'Steward', 'Dorothy_Mackenzie4447@deons.tech', 'Dorothy Mackenzie', 'False', 5)
(41, 'Front Desk Coordinator', 'Elena_Gregory8402@ubusive.com', 'Elena Gregory', 'True', 15)
(42, 'Production Painter', 'Helen_Adams3473@guentu.biz', 'Helen Adams', 'True', 15)
(43, 'Software Engineer', 'Lucas_Brooks385@typill.biz', 'Lucas Brooks', 'False', 5)
(44, 'Cook', 'Angelina_Ross7491@qater.org', 'Angelina Ross', 'True', 15)
(45, 'Biologist', 'Remy_Benfield4958@kideod.biz', 'Remy Benfield', 'True', 15)
(46, 'IT Support Staff', 'Mackenzie_Neal4273@qater.org', 'Mackenzie Neal', 'True', 15)
(47, 'Associate Professor', 'Janelle_Parker3414@twace.org', 'Janelle Parker', 'True', 15)
(48, 'Treasurer', 'Matthew_Woodley2830@gembat.biz', 'Matthew Woodley', 'True', 15)
(49, 'Ambulatory Nurse', 'Anthony_Coleman4896@nanoff.biz', 'Anthony Coleman', 'True', 15)
(50, 'Restaurant Manager', 'Peyton_Hobson4407@iatim.tech', 'Peyton Hobson', 'True', 15)

In [22]:
df = pd.read_sql_query("SELECT * FROM employee", connection)

In [23]:
df.head()

,id,JobTitle,EmailAddress,FirstNameLastName,vaccinated,bonus_percent
0,1,Designer,Leroy_Yarlett52@guentu.biz,Leroy Yarlett,False,5
1,2,Webmaster,Julian_Gonzales8496@famism.biz,Julian Gonzales,True,15
2,3,Paramedic,George_Porter6363@deons.tech,George Porter,False,5
3,4,IT Support Staff,Penny_Reynolds8665@supunk.biz,Penny Reynolds,False,5
4,5,Dentist,Gabriel_Upton1432@bungar.biz,Gabriel Upton,True,15

In [33]:
connection.close()